### ISSUE TITLE
No longer scraping properly

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/willoughby#5]
https://morph.io/planningalerts-scrapers/willoughby is passing, but https://www.planningalerts.org.au/authorities/willoughby indicates something is wrong.

Looking at the system there's def. newer development applications available within the last 30 days

**Comment by LoveMyData** [comment]
@CloCkWeRX , I think it is fixed with 0001c933eb06c6abe322c1d4973f9f2a1266644d commit, can you pls double check before we close this issue?

**Comment by CloCkWeRX** [comment]
woo
